last update from old macbook

diff --git a/configserver/Dockerfile b/configserver/Dockerfile
--- a/configserver/Dockerfile
+++ b/configserver/Dockerfile
@@ -10,7 +10,8 @@ FROM openjdk:8-jre-alpine
 MAINTAINER Mick Knutson <mknutson@baselogic.io>
 
 LABEL DESCRIPTION="This container is a Spring Cloud Configuration Server"
-#USER nobody
+
+
 
 ##---------------------------------------------------------------------------##
 ## ARG's
@@ -60,10 +61,9 @@ ADD ./build/libs/*-exec.jar ${APPLICATION_PATH}/application-exec.jar
 
 
 ##---------------------------------------------------------------------------##
-ENV APK_ADD="bash curl httpie"
-#ENV APK_ADD="bash curl busybox httpie"
-ENV APK_DEL="curl httpie"
-#ENV APK_DEL="curl busybox httpie"
+## NOTE: Running commands in-line
+#ENV APK_ADD="bash curl httpie"
+#ENV APK_DEL="bash curl httpie"
 
 
 # NOTE: RUN is run when building the image NOT when running the container:
@@ -72,7 +72,6 @@ ENV APK_DEL="curl httpie"
 #RUN apk add --no-cache ${APK_ADD}
 
 
-##---------------------------------------------------------------------------##
 # NOTE: Clean up files not needed for running the container:
 
 #RUN rm -rf /usr/share/man/*
@@ -84,13 +83,21 @@ ENV APK_DEL="curl httpie"
 #RUN rm -rf /usr/lib/node_modules/npm/html/*
 #RUN rm -rf /usr/lib/node_modules/npm/scripts/*
 
+
+
+
+
+
+
+
+
+##---------------------------------------------------------------------------##
 # NOTE: RUN is run when building the image NOT when running the container:
 #RUN apk update && \
 #    apk upgrade && \
 #    apk add --no-cache ${APK_ADD}
 
 
-##---------------------------------------------------------------------------##
 # NOTE: Clean up files not needed for running the container:
 #RUN rm -rf \
 #      /usr/share/man/* \
@@ -104,32 +111,51 @@ ENV APK_DEL="curl httpie"
 
 #RUN apk del ${APK_DEL}
 
-## Option to externalize the OS commands:
+
+
+
+
+
+
+
+
+
+
+
+##---------------------------------------------------------------------------##
+## NOTE: Option to externalize the OS commands:
 COPY ./*container-start.sh ${APPLICATION_PATH}/
 
 RUN chmod -v +x ./container-start.sh && \
     ./container-start.sh && \
     rm ./container-start.sh
 
-# Now create a new USER and make them the owner of our application files:
+
+
+
+
+
+
+##---------------------------------------------------------------------------##
+# NOTE: Now create a new USER and make them the owner of our application files:
 RUN adduser -H -D ${USERNAME} -u ${USER_ID} && \
     chown ${USERNAME}:${USERNAME} -R ${APPLICATION_PATH}/
 
 ##---------------------------------------------------------------------------##
-# NOTE: We should not run the application as root !
+# NOTE: Switch the running user. We should not run the application as root !
 #USER spring
 USER ${USERNAME}
 
 ##---------------------------------------------------------------------------##
 # NOTE: RUN is run when building the image NOT when running the container:
 # NOTE: CMD is run when starting the container NOT when creating the image:
-RUN echo "$NOTE_RUN"
-#CMD echo "$NOTE_RUN"
+RUN echo "RUN $NOTE_RUN"
+CMD echo "CMD $NOTE_RUN"
 
 
 ##---------------------------------------------------------------------------##
 # Note: Which ports to expose to the outside host
-# Can be enabled and/or overridden with -e, -p, docker-compose
+# Can be enabled and/or overridden with -e (ENV), -p (PORT), docker-compose
 # -e [HOST:CONTAINER]
 # -p [HOST:CONTAINER]
 #EXPOSE $PORT
@@ -154,12 +180,20 @@ ENTRYPOINT java -Djava.security.egd=file:/dev/./urandom -jar ./application-exec.
 #
 # To verify status:
 # http://container:port/health --> JSON happy or not
-# docker inspect --format "{{json .State.Health.Status }}" microservicesclient
+# docker inspect --format "{{json .State.Health.Status }}" configserver
 
-ARG HEALTHCHECK_URI=http://localhost:$PORT/health
+ENV HEALTHCHECK_URI=localhost:$PORT/health
 
 # Spring Boot Actuator: TODO: Revisit syntax:
-HEALTHCHECK --interval=5m --timeout=2s --retries=3 CMD curl -v --silent $HEALTHCHECK_URI 2>&1
+HEALTHCHECK --interval=10s --timeout=2s --retries=3 \
+    CMD curl -v --silent $HEALTHCHECK_URI 2>&1
+
+#HEALTHCHECK --interval=10s --timeout=3s --retries=3 \
+#    CMD curl -f $HEALTHCHECK_URI || exit 1
+
+#HEALTHCHECK --interval=10s --timeout=3s --retries=3 \
+#    CMD ["http","$HEALTHCHECK_URI"]
+
 
 ##---------------------------------------------------------------------------##
 ##---------------------------------------------------------------------------##
diff --git a/microservicesclient/Dockerfile b/microservicesclient/Dockerfile
--- a/microservicesclient/Dockerfile
+++ b/microservicesclient/Dockerfile
@@ -50,37 +50,15 @@ ADD ./build/libs/*-exec.jar ${APPLICATION_PATH}/application-exec.jar
 
 
 ##---------------------------------------------------------------------------##
-ENV APK_ADD="bash curl httpie"
-#ENV APK_ADD="bash curl busybox httpie"
-ENV APK_DEL="curl httpie"
-#ENV APK_DEL="curl busybox httpie"
+## Option to externalize the OS commands:
+COPY ./*container-start.sh ${APPLICATION_PATH}/
 
-# NOTE: RUN is run when building the image NOT when running the container:
-#RUN apk update && \
-#    apk upgrade && \
-#    apk add --no-cache ${APK_ADD}
+RUN chmod -v +x ./container-start.sh && \
+    ./container-start.sh && \
+    rm ./container-start.sh
 
 
 ##---------------------------------------------------------------------------##
-# NOTE: Clean up files not needed for running the container:
-#RUN rm -rf \
-#      /usr/share/man/* \
-#      /usr/includes/* \
-#      /var/cache/apk/* \
-#      /root/.npm/* \
-#      /usr/lib/node_modules/npm/man/* \
-#      /usr/lib/node_modules/npm/doc/* \
-#      /usr/lib/node_modules/npm/html/* \
-#      /usr/lib/node_modules/npm/scripts/*
-
-#RUN apk del ${APK_DEL}
-
-## Option to externalize the OS commands:
-#COPY ./*container-start.sh ${APPLICATION_PATH}/
-#RUN chmod -v +x ./container-start.sh && \
-#    ./container-start.sh && \
-#    rm ./container-start.sh
-
 # Now create a new USER and make them the owner of our application files:
 RUN adduser -H -D ${USERNAME} -u ${USER_ID} && \
     chown ${USERNAME}:${USERNAME} -R ${APPLICATION_PATH}/
@@ -122,10 +100,18 @@ ENTRYPOINT java -Djava.security.egd=file:/dev/./urandom -jar ./application-exec.
 # http://container:port/health --> JSON happy or not
 # docker inspect --format "{{json .State.Health.Status }}" microservicesclient
 
-ARG HEALTHCHECK_URI=http://localhost:$PORT/health
+ENV HEALTHCHECK_URI=localhost:$PORT/health
 
-# Spring Boot Actuator:
-HEALTHCHECK --interval=5m --timeout=2s --retries=3 CMD curl -v --silent $HEALTHCHECK_URI 2>&1
+# Spring Boot Actuator: TODO: Revisit syntax:
+HEALTHCHECK --interval=10s --timeout=2s --retries=3 \
+    CMD curl -v --silent $HEALTHCHECK_URI 2>&1
+
+#HEALTHCHECK --interval=10s --timeout=3s --retries=3 \
+#    CMD curl -f $HEALTHCHECK_URI || exit 1
+
+#HEALTHCHECK --interval=10s --timeout=3s --retries=3 \
+#    CMD ["http","$HEALTHCHECK_URI"]
+
 
 ##---------------------------------------------------------------------------##
 ##---------------------------------------------------------------------------##
